name: PyTest

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Coverage Report
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install 'sequences' Package and Dependencies
        run: pip install --upgrade --upgrade-strategy eager .[test]

      - name: Install PyTest GitHub Annotation Plugin
        run: pip install pytest-github-actions-annotate-failures

      - name: Run PyTest and Generate Coverage Report
        run: |
          pytest -n 4 --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered --cov=sequences | tee pytest-coverage.txt

      - name: Verify PyTest XML Output
        run: |
          if [ ! -f pytest.xml ]; then
            echo "PyTest XML report not found. Please check the previous 'Run PyTest' step for errors."
            exit 1
          fi

      - name: Post PyTest Coverage Comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@v1.1.53
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      - name: Set Pipeline Status Based on Test Results
        if: steps.coverageComment.outputs.errors != 0 || steps.coverageComment.outputs.failures != 0
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed("PyTest workflow failed with ${{ steps.coverageComment.outputs.errors }} errors and ${{ steps.coverageComment.outputs.failures }} failures.")

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true
